package com.github.rojekp.spm.domain.exception;

public enum ErrorCode {

    TEAM_ALREADY_EXISTS,
    EMPTY_TEAM_NAME,
    NONEXISTENT_TEAM,
    EMPTY_MEMBER_FIRST_NAME,
    EMPTY_MEMBER_LAST_NAME,
    INVALID_MEMBER_JOB_POSITION,
    EMPTY_PROJECT_NAME,
    EMPTY_PROJECT_IDENTIFIER

}
